### ISSUE TITLE
About the model order

### ISSUE THREAD

**Issue by gaorunzebit** [AleksandarHaber/Subspace-Identification-State-Space-System-Identification-of-Dynamical-Systems-and-Time-Series-#1]
Hello Dr. Haber,

I notice that you set the system order by yourself. Acutally, refer to [Van Overschee, De Moor 1994], they found the system order is equal to the rank of S, which is the singular value of oblique projection. But in my code, it's hard to determine the singular value's rank. The rank is always unequal to the original system order in numerical compuation. Have you met this question. and how to solve it? 

Thank you!
Runze

**Comment by AleksandarHaber** [comment]
Hi Runze,

The problem of determining the system order is a challenging one. Several approaches have been proposed in the literature. A heuristic approach is to try to identify a gap in the singular values of a data matrix. Another approach is to compute the Variance Accounted For (VAF) for increasing state orders and to select the state order that gives the highest variance accounted for. Also, it is necessary to determine the order of the VARX model. This can effectively be done by using the Akaike Information Criterion. 
For more details, see this paper that contains experimental results:

https://arxiv.org/pdf/1908.02379.pdf

Best Regards,
Aleksandar
