### ISSUE TITLE
about  portmanteau function

### ISSUE THREAD

**Issue by bin147258** [AleksandarHaber/Subspace-Identification-State-Space-System-Identification-of-Dynamical-Systems-and-Time-Series-#2]
Hello Dr. Haber,

I'm working with the Portmanteau function and had a question about the m_max parameter. Does it refer to the length of the validation data, or is it related to the maximum lag in autocovariance/correlation calculations?

Thanks for your help!
Bin Guo

<img width="296" alt="Snipaste_2024-02-28_16-00-17" src="https://github.com/AleksandarHaber/Subspace-Identification-State-Space-System-Identification-of-Dynamical-Systems-and-Time-Series-/assets/115568955/13986be4-6114-43d6-a931-c04754efba6b">

**Comment by AleksandarHaber** [comment]
1.) DO NOT POST HERE YOUR QUESTIONS
2.) I DO NOT HAVE TIME AND ENERGY TO PROVIDE YOU WITH FREE ANSWERS!
